### ISSUE TITLE
Using `flipboxstudio/api-manager`

### ISSUE THREAD

**Issue by aqidd** [flipboxstudio/web-3.0#1]
How about using https://github.com/flipboxstudio/api-manager as the base structure?

**Comment by krisanalfa** [comment]
[Flipbox API Manager](https://github.com/flipboxstudio/api-manager) is built for Laravel (full framework), while this design uses Lumen. So I think there's a problem with that.

> API return standard defined inside this design under `src/Fractal` directory. Please have a look at [this](https://github.com/flipboxstudio/web-3.0/blob/develop/backend/src/Fractal/Serializers/FlipboxSerializer.php#L139).

So, for now I can say:
- This design is lack of endpoint versioning
- Need some API documentation generator

I will leave this issue open for discussion later.

**Comment by krisanalfa** [comment]
We need to rewrite Flipbox API Manager to support Lumen. There's generator inside this skeleton, so feel free to extend it's functionality.

**Comment by krisanalfa** [comment]
Move this issue to `stack-backend`.
